import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'
import homeImage from '../assets/homeImage.png'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i0.wp.com/www.downloadfonts.io/wp-content/uploads/2022/01/Rick-and-Morty-Font-Family-Free-Download-735x400-1.jpg?resize=735%2C400&ssl=1" />
      </Head>
      <main>
        <div className='border-8 border-slate-400 bg-slate-900 p-8 my-4 rounded-[4em] h-[700px]'>
          <h1 className='text-center mt-6 font-extrabold text-[2em] bg-slate-600 text-slate-100 p-4 w-full rounded-[3em]'>Welcome to Rick and Morty Characters Webpage</h1>
          <Image
            src={homeImage}
            alt="Home Image"
            width={900}
            height={900}
            className="mx-auto rounded-[30em] my-4"
          />
          <div className='flex justify-center mt-4'>
            <Link href="/about" className='text-blue-900 ml-4 text-[2em]'>
              <button className='border bg-slate-600 p-8 rounded-[4em] text-slate-100 hover:text-[1.2em] hover:bg-slate-400 hover:font-bold'>About Rick and Morty</button>
            </Link>
            <Link href={"/characters"} className='text-blue-900 ml-4 text-[2em]'>
              <button className='border bg-slate-600 p-8 rounded-[4em] text-slate-100 hover:text-[1.2em] hover:bg-slate-400 hover:font-bold'>See characters of Rick and Morty</button>
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
}



export default Home;